title: Neocities Documentation
description: A practical guide to creating and publishing a Neocities website.
url: "https://turning20w-hub.github.io"
baseurl: "/technical-documentation-project"

theme: jekyll-theme-minimal

markdown: kramdown

permalink: pretty

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
